### PR TITLE
upgrade monorepo setup to 2022

### PR DESCRIPTION
**Pull request by kamlekar**

### CODE REVIEW

**Comment by kamlekar** [comment]
Ok. I wasn't aware the PR would be created in the base repo. Anyway, it is good to be considered here too.  It is up to you Author. 
This work is still in progress. I can't make this a draft PR.

**Comment by kamlekar** [comment]
FYI, noting down the issues I have to still work on:
- Storybook setup isn't happening
- Though the app start is working, the UI's look & feel are gone
- VS code throwing random module not found errors. I guess I should work on proper tsconfig changes. Any help is appreciated.

Let me know if you find any other issues.

**Comment by kamlekar** [comment]
Cool. Let’s see how much I go with upgrading it. It is still in progress. I am doing it whenever I get time. 

Strangely, when I tried to do fresh monorepo setup it didn’t work. So I fork this which was working great but needed upgrade to packages. Thanks for this btw. 

My roadmap is to create ui, backend and components packages - with in-built oauth, deployment stuff, fundamental components etc so people can fork and focus on their ideas more than worrying about login, deploying etc. (is there something like this already?) 

I am planning to use strapi for backend in future. Coming to maintaining this, I don’t think I can actively maintain this as my idea is something else as mentioned above.

I am learning as I do this. I will keep the PR and updated it (will inform once done) and leave it on you to do as you wish :). Thanks!

I don’t mind if you close this too.

**Comment by cadbox1** [comment]
hey @kamlekar,

I made my last comment from the wrong github account so I've deleted it now. sorry about that.

I like your plan! there's probably a few options out there for that but I personally like building my own 'boilerplate' projects so I can understand the tools better and for extra flexibility when I need it. 

I've actually done a bit of work with auth. are you planning to use oauth or something lighter? are you going to integrate with Auth0?

happy to bounce some ideas off you if you need it. it sounds cool.

coming back to this PR, I reckon we close it because it's something much bigger than this repo's direction, like you said.

keep up the good work!

cheers,

cadell

**Comment by kamlekar** [comment]
All good. Thanks @cadbox1. I am thinking strapi can be used to handle authentication from social networks. I haven’t explored this yet. Would appreciate any suggestions here if you can. I am still stuck with upgrading packages. Looks like everything is done but the app ui isn’t showing the content.

**Pull request closed without merging**
